Add styles for app
marvin-nyalik/bookstore-redux pull request #6
Opened 2023-07-18 16:27 UTC by marvin-nyalik

In this branch:

- I added detailed styling for the application using the Zeplin design template.
- Matched my final styles with the design

Let me know of required changes.

2023-07-18 17:39 UTC, OyePriscilla requested changes
Hi @marvin-nyalik 👏, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![so-close](https://user-images.githubusercontent.com/103386183/196423863-0f522555-1b03-455e-a452-b822cdcfc398.gif)

## Highlights
All elements in design added 👍 
Styling is **EXACTLY** the same as the one provided on [Zeplin](https://zeplin.io/) ❎ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-18 17:39 UTC, OyePriscilla commented on src/components/info.module.css
> +  }
Kindly place the percentage text out of the progress label and don't forget to add completed text. ℹ️

2023-07-18 17:39 UTC, OyePriscilla commented on src/components/addBook.module.css
> +  }
- [ ] Kindly implement correct background-color in accordance with the design (the body element inclusive). 👍

2023-07-18 17:39 UTC, OyePriscilla commented on src/components/addBook.module.css
> +  }
- [ ] I observed that there is difference between your design and the given template. It's stated in the requirement that design should be close to Zeplin's design. Kindly adjust the margin around the `nav` items, design the `remove` button expected and the `hr` element that is missing.

## Template
<img width="528" alt="Untitled" src="https://github.com/marvin-nyalik/bookstore-redux/assets/103386183/2a3d1ad9-202a-4125-87e7-e782caaf16ec">

## Your Design

<img width="910" alt="Untitled" src="https://github.com/marvin-nyalik/bookstore-redux/assets/103386183/a03d27f7-7675-40e4-8565-34831a40b4cd">

2023-07-18 17:39 UTC, OyePriscilla commented on src/components/info.module.css
> +  }
- [ ] Kindly increase the left margin in accordance to the template. 👍

2023-07-19 09:16 UTC, AlphaNtihinduka approved these changes
# STATUS: APPROVED :green_circle: :clap: 
## Hi @marvin-nyalik 🙋‍♂️, 

Your project is complete!  There is nothing else to say other than... Great job 👏 

![approved-accepted](https://user-images.githubusercontent.com/99394374/212473432-e725752b-8682-4dbb-993e-9e466dbe7acb.gif)

Congratulations! 🎉 
TO HIGHLIGHT:

- All elements in design added 👍
- Styling is EXACTLY the same as the one provided on [Zeplin](https://zeplin.io/) ❎
- Well-structured files :heavy_check_mark: 

Now you can merge this branch and move on :1st_place_medal: 


## Optional suggestions
- Kindly refer to the inline optional suggestions made. Ensure to apply them to have a professional project that suits recruiters' needs.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

HAPPY CODING AND GOOD LUCK WITH THE COMING ONES :crossed_fingers: :four_leaf_clover:

2023-07-19 10:54 UTC, merged